package packets

const (
	PACKET_TYPE_INVALID           = 0x0
	PACKET_TYPE_NOT_A_BLOCK       = 0x1
	PACKET_TYPE_KEEPALIVE         = 0x2
	PACKET_TYPE_PUBLISH           = 0x3
	PACKET_TYPE_CONFIRM_REQ       = 0x4
	PACKET_TYPE_CONFIRM_ACK       = 0x5
	PACKET_TYPE_BULK_PULL         = 0x6
	PACKET_TYPE_BULK_PUSH         = 0x7
	PACKET_TYPE_FRONTIER_REQ      = 0x8
	PACKET_TYPE_NODE_ID_HANDSHAKE = 0x0a
	PACKET_TYPE_BULK_PULL_ACCOUNT = 0x0b
	PACKET_TYPE_TELEMETRY_REQ     = 0x0c
	PACKET_TYPE_TELEMETRY_ACK     = 0x0d
)

const (
	BLOCK_TYPE_INVALID     = 0x00
	BLOCK_TYPE_NOT_A_BLOCK = 0x01
	BLOCK_TYPE_SEND        = 0x02
	BLOCK_TYPE_RECEIVE     = 0x03
	BLOCK_TYPE_OPEN        = 0x04
	BLOCK_TYPE_CHANGE      = 0x05
	BLOCK_TYPE_STATE       = 0x06
)

const PROTOCOL_VERSION byte = 18
